# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from .actions import (ACTION_CREATE, ACTION_CREATE_DEPENDENCY, ACTION_CREATE_ATTACHED,
                      ACTION_CREATE_DEPENDENCY_ATTACHED, ACTION_START, ACTION_START_DEPENDENCY, ACTION_START_ATTACHED,
                      ACTION_START_DEPENDENCY_ATTACHED, ACTION_PREPARE_ATTACHED, ACTION_PREPARE_DEPENDENCY_ATTACHED,
                      ACTION_RESTART, ACTION_RESTART_DEPENDENCY, ACTION_STOP, ACTION_STOP_DEPENDENT,
                      ACTION_REMOVE, ACTION_REMOVE_DEPENDENT, ACTION_REMOVE_ATTACHED, ACTION_REMOVE_DEPENDENT_ATTACHED,
                      ACTIONS_CREATE, ACTIONS_START, ACTIONS_PREPARE, ACTIONS_RESTART, ACTIONS_STOP, ACTIONS_REMOVE)

from .simple import SimplePolicy
