# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from collections import namedtuple


ACTION_CREATE = 10
ACTION_CREATE_DEPENDENCY = 12
ACTION_CREATE_ATTACHED = 15
ACTION_CREATE_DEPENDENCY_ATTACHED = 17
ACTION_START = 20
ACTION_START_DEPENDENCY = 22
ACTION_START_ATTACHED = 25
ACTION_START_DEPENDENCY_ATTACHED = 27
ACTION_PREPARE_ATTACHED = 30
ACTION_PREPARE_DEPENDENCY_ATTACHED = 32
ACTION_STOP = 50
ACTION_STOP_DEPENDENT = 52
ACTION_REMOVE = 60
ACTION_REMOVE_DEPENDENT = 62
ACTION_REMOVE_ATTACHED = 65
ACTION_REMOVE_DEPENDENT_ATTACHED = 67

ACTIONS_CREATE = ACTION_CREATE, ACTION_CREATE_DEPENDENCY, ACTION_CREATE_ATTACHED, ACTION_CREATE_DEPENDENCY_ATTACHED
ACTIONS_START = ACTION_START, ACTION_START_DEPENDENCY, ACTION_START_ATTACHED, ACTION_START_DEPENDENCY_ATTACHED
ACTIONS_PREPARE = ACTION_PREPARE_ATTACHED, ACTION_PREPARE_DEPENDENCY_ATTACHED
ACTIONS_STOP = ACTION_STOP, ACTION_STOP_DEPENDENT
ACTIONS_REMOVE = ACTION_REMOVE, ACTION_REMOVE_DEPENDENT, ACTION_REMOVE_ATTACHED, ACTION_REMOVE_DEPENDENT_ATTACHED

ContainerAction = namedtuple('ContainerAction', ('action', 'map_name', 'container', 'kwargs'))
